### ISSUE TITLE
Context.tf out of date?

### ISSUE THREAD

**Issue by ekristen** [cloudposse/terraform-aws-named-subnets#28]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Seems like the context.tf is out of date compared to others with respect to null-label? The current null-label is pointing to a version that doesn't work with tf 0.14.0

## Expected Behavior
I would expect null-label to be updated to the latest version especially since there seems to be an auto-update process.

**Comment by Nuru** [comment]
Closed by #33
